In [1]:
from numpy import random

In [3]:
x = random.randint(1,100, size=(random.randint(1,50),random.randint(1,40)))

In [7]:
x

array([[47, 73, 61, ..., 87, 47,  2],
       [53, 78,  4, ..., 50, 90,  3],
       [27,  6, 70, ..., 35, 50, 17],
       ...,
       [56, 31, 54, ..., 36, 23, 91],
       [42, 22,  2, ..., 63, 81, 52],
       [22, 85, 23, ...,  7, 20, 44]])

In [9]:
x[2,:]

array([27,  6, 70, 30, 69, 95, 62, 86, 58, 21, 51, 86, 86, 97, 90, 12, 27,
       63, 84, 89, 84, 61, 54, 89, 22, 17, 93, 96, 78, 35, 50, 17])

In [10]:
x[:,2]

array([61,  4, 70, 95, 83, 34, 51, 90, 64, 56, 56, 25, 79, 62, 30, 49, 47,
       93, 63, 77, 36, 16, 49, 74,  5,  4, 57, 54, 20, 60, 67, 22, 49, 73,
       15, 58,  7, 85, 71,  3, 79, 82, 61, 45, 14, 54,  2, 23])

In [11]:
x[-1]=7

In [12]:
x

array([[47, 73, 61, ..., 87, 47,  2],
       [53, 78,  4, ..., 50, 90,  3],
       [27,  6, 70, ..., 35, 50, 17],
       ...,
       [56, 31, 54, ..., 36, 23, 91],
       [42, 22,  2, ..., 63, 81, 52],
       [ 7,  7,  7, ...,  7,  7,  7]])

In [14]:
x[:,-1]=x[:,0]+x[:,1]

In [15]:
x

array([[ 47,  73,  61, ...,  87,  47, 120],
       [ 53,  78,   4, ...,  50,  90, 131],
       [ 27,   6,  70, ...,  35,  50,  33],
       ...,
       [ 56,  31,  54, ...,  36,  23,  87],
       [ 42,  22,   2, ...,  63,  81,  64],
       [  7,   7,   7, ...,   7,   7,  14]])