## Question 1

In [2]:
import numpy as np

In [15]:
arr =np.arange(6,100,4)

In [11]:
arr

array([ 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70,
       74, 78, 82, 86, 90, 94, 98])

## Question 2

In [47]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [41]:
a = a[~np.isnan(a)]

In [42]:
a

array([1., 2., 3., 5., 6., 7.])

In [48]:
a=[value for value in a if not np.isnan(value)]

In [49]:
a

[1.0, 2.0, 3.0, 5.0, 6.0, 7.0]

## Question 3

In [51]:
from numpy import random

In [55]:
x = random.randint(1,100, size=(5,6)

In [56]:
x

array([[79, 19, 46, 25, 76, 80],
       [20,  4, 82, 41, 22, 29],
       [32,  6, 53, 35, 89, 71],
       [60, 32, 69, 87, 89, 30],
       [26, 41, 79, 98, 23,  4]])

In [57]:
x.max(1)

array([80, 82, 89, 89, 98])

## Question 4

In [74]:
import pandas as pd

In [75]:
series = pd.Series(np.take(list('abcdefghijklmnop'), np.random.randint(16, size=500)))

In [77]:
series.value_counts()

f    40
l    38
b    37
i    37
k    35
n    34
g    33
h    32
e    30
a    30
c    28
d    28
m    27
o    26
j    23
p    22
dtype: int64

## Question 5

In [60]:
import pandas as pd

In [61]:
series = pd.Series(['01 Jan 2020', '10-19-2020', '20150303', '2013/04/04', '2012-05-05', '2013-06-06T12:20'])


In [68]:
from dateutil.parser import parse
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
date_series = date_series.map(lambda x: parse(x))
print("Day of month:")
print(date_series.dt.day.tolist())
print("Week number:")
print(date_series.dt.isocalendar().week.tolist())
print("Day of year:")
print(date_series.dt.dayofyear.tolist())
print("Day of week:")
print(date_series.dt.day_name().tolist())

Day of month:
[1, 2, 7, 6, 12, 6]
Week number:
[1, 39, 10, 19, 15, 14]
Day of year:
[1, 276, 66, 126, 103, 96]
Day of week:
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']


## Question 6

In [81]:
from matplotlib import pyplot as plt

In [82]:
url='https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)

In [85]:
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [86]:
df.rename(columns = {'Type': 'TypeofCar'})

Manufacturer    Model TypeofCar  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra     Small       12.9   15.9       18.8      25.0   
1           NaN   Legend   Midsize       29.2   33.9       38.7      18.0   
2          Audi       90   Compact       25.9   29.1       32.3      20.0   
3          Audi      100   Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i   Midsize        NaN   30.0        NaN      22.0   
..          ...      ...       ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan       Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat   Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado    Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240   Compact       21.8   22.7       23.5      21.0   
92          NaN      850   Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [91]:
df.isnull().sum().sum()

138

In [92]:
for col in df.columns:
    print(col,df[col].isnull().sum())

Manufacturer 4
Model 1
Type 3
Min.Price 7
Price 2
Max.Price 5
MPG.city 9
MPG.highway 2
AirBags 6
DriveTrain 7
Cylinders 5
EngineSize 2
Horsepower 7
RPM 3
Rev.per.mile 6
Man.trans.avail 5
Fuel.tank.capacity 8
Passengers 2
Length 4
Wheelbase 1
Width 6
Turn.circle 5
Rear.seat.room 4
Luggage.room 19
Weight 7
Origin 5
Make 3


## Question 7

In [93]:
del df['EngineSize']

In [94]:
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [95]:
df.drop(['Length'], axis = 1, inplace = True) 

In [96]:
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Wheelbase', 'Width', 'Turn.circle',
       'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin', 'Make'],
      dtype='object')

## Question 8